### PR TITLE
Contribute our calendar provider API and implementation

### PR DESCRIPTION
**Pull request by benbucksch**

### CODE REVIEW

**Comment by benbucksch** [comment]
PRs so far:
* Allow the extension to opt-in to sending invitations and responses #19
* Always merge items where possible #18
* Support email calendar property #17
* Add ability to synchronise a single calendar #16
* Ability to get all metadata #15 
* Make onItemRemoved provider notification work #14
* Properly support -1 categories #13
* Make updating event start and end time work #12
* Use the id that the cache storage layer expects the metadata to use #11 
* Make getting cached calendars work #10
* Make optional options really optional #9
* Preserve the extension calendar cache on shutdown #8

**Comment by kewisch** [comment]
@benbucksch , how do you want to proceed with this PR? I see the other PRs are an effort to take the good parts from your proposal into the one already part of the repo. Do you want to leave this open until all that is done? Do you want to merge this with a disclaimer in the readme? Or close this in favor of the main implementation and future PRs?

**Comment by benbucksch** [comment]
@kewisch : I don't quite understand questions 2 and 3.

We'd be happy to have this implementation here in this PR merged into Thunderbird.

The other PRs are there in case you prefer your implementation. We tried to port all features we need onto your implementation.

Whatever path is chosen, this ticket should stay open until the calendar API (either implementation) supports all these features, properly and without hacks.

**Comment by benbucksch** [comment]
[updated last comment]

**Comment by kewisch** [comment]
These were either-or questions. My preference would be to work on one API, to me it looks like the best path forward would be to port your API to the other experiment API as you have been with above pull requests.

**Comment by benbucksch** [comment]
Well, the easiest way forward would be to just take our implementation and merge it into Thunderbird as official API. But I understand that you might not want to do that, that's why we pushed the PRs.

As I said, as long as the end result has all features, and works without hacks in our ext, either way is fine for me.

**Comment by kewisch** [comment]
Great, sounds good to me! I'll close this PR then and we can continue collaborating through other PRs against the `calendar/` experiment. Thank you for sending all those great PRs and improving, it is much appreciated!

**Comment by benbucksch** [comment]
> Thank you for sending all those great PRs and improving, it is much appreciated!

With pleasure!

**Pull request closed without merging**
