### PR TITLE
Update provider to Thunderbird 102

### PR DESCRIPTION
**Pull request by kewisch**
@jobisoft I made a start on this, but ran out of time to debug. Try running the extension provided by the experiment and you'll see an unexpected error because of some missing function.

### CODE REVIEW

**Comment by kewisch** [comment]
This is almost ready for review. I wanted to drop my current state as it at least doesn't throw errors. I need to clean up and double check though.

**Comment by jobisoft** [comment]
I was hold up with my patch for https://phabricator.services.mozilla.com/D146689 which took much longer than expected. I try to get to this very very soon.

**Comment by kewisch** [comment]
This should be good to go, let me know if you see something I missed

**Comment by jobisoft** [comment]
[rsjtdrjgfuzkfg](https://github.com/rsjtdrjgfuzkfg) confirmed that it is working. Thanks for both of your work!

**Pull request merged**
